# Generated by Django 2.2.4 on 2019-09-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_input', models.CharField(max_length=200)),
                ('pub_time', models.DateTimeField(verbose_name='time entered')),
            ],
        ),
    ]
